// Generated by Bisonc++ V2.09.03 on Wed, 12 Mar 2014 21:22:58 +0530

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {300, 4}, // 1: program ->  declaration_statement_list function_declaration_list #0001 procedure_list
     {303, 0}, // 2: #0001 ->  <empty>
     {300, 2}, // 3: program ->  function_declaration_list procedure_list
     {301, 2}, // 4: function_declaration_list ->  function_declaration_list function_declaration
     {301, 1}, // 5: function_declaration_list ->  function_declaration
     {304, 6}, // 6: function_declaration (NAME) ->  type NAME '(' argument_list ')' ';'
     {304, 6}, // 7: function_declaration (VOID) ->  VOID NAME '(' argument_list ')' ';'
     {304, 5}, // 8: function_declaration (NAME) ->  type NAME '(' ')' ';'
     {304, 5}, // 9: function_declaration (VOID) ->  VOID NAME '(' ')' ';'
     {305, 3}, // 10: argument_list (',') ->  argument_list ',' argument
     {305, 1}, // 11: argument_list ->  argument
     {306, 2}, // 12: argument (NAME) ->  type NAME
     {307, 1}, // 13: type (INTEGER) ->  INTEGER
     {307, 1}, // 14: type (FLOAT) ->  FLOAT
     {307, 1}, // 15: type (DOUBLE) ->  DOUBLE
     {302, 1}, // 16: procedure_list ->  procedure
     {302, 2}, // 17: procedure_list ->  procedure_list procedure
     {308, 6}, // 18: procedure (NAME) ->  NAME '(' argument_list ')' #0002 procedure_body
     {310, 0}, // 19: #0002 ->  <empty>
     {308, 5}, // 20: procedure (NAME) ->  NAME '(' ')' #0003 procedure_body
     {311, 0}, // 21: #0003 ->  <empty>
     {309, 5}, // 22: procedure_body ('{') ->  '{' declaration_statement_list #0004 basic_block_list '}'
     {312, 0}, // 23: #0004 ->  <empty>
     {309, 3}, // 24: procedure_body ('{') ->  '{' basic_block_list '}'
     {313, 1}, // 25: declaration_statement_list ->  declaration_statement
     {313, 2}, // 26: declaration_statement_list ->  declaration_statement_list declaration_statement
     {314, 3}, // 27: declaration_statement (NAME) ->  type NAME ';'
     {315, 2}, // 28: basic_block_list ->  basic_block_list basic_block
     {315, 1}, // 29: basic_block_list ->  basic_block
     {316, 3}, // 30: basic_block (BASIC_BLOCK) ->  BASIC_BLOCK ':' executable_statement_list
     {316, 4}, // 31: basic_block (BASIC_BLOCK) ->  BASIC_BLOCK ':' executable_statement_list conditional_statement
     {316, 4}, // 32: basic_block (BASIC_BLOCK) ->  BASIC_BLOCK ':' executable_statement_list goto_statement
     {317, 1}, // 33: executable_statement_list ->  statement_list
     {317, 3}, // 34: executable_statement_list (';') ->  statement_list return_statement ';'
     {318, 1}, // 35: return_statement (RETURN) ->  RETURN
     {318, 2}, // 36: return_statement (RETURN) ->  RETURN exp_assign_op
     {319, 0}, // 37: statement_list ->  <empty>
     {319, 2}, // 38: statement_list ->  statement_list assignment_statement
     {319, 3}, // 39: statement_list (';') ->  statement_list function_call_statement ';'
     {320, 4}, // 40: assignment_statement (ASSIGN_OP) ->  variable ASSIGN_OP exp_assign_op ';'
     {321, 4}, // 41: function_call_statement (NAME) ->  NAME '(' exp_assign_op_list ')'
     {321, 3}, // 42: function_call_statement (NAME) ->  NAME '(' ')'
     {322, 3}, // 43: exp_assign_op_list (',') ->  exp_assign_op_list ',' exp_assign_op
     {322, 1}, // 44: exp_assign_op_list ->  exp_assign_op
     {323, 1}, // 45: variable (NAME) ->  NAME
     {323, 4}, // 46: variable ('(') ->  '(' type ')' NAME
     {324, 1}, // 47: constant (INTEGER_NUMBER) ->  INTEGER_NUMBER
     {324, 1}, // 48: constant (FLOATING_POINT_NUMBER) ->  FLOATING_POINT_NUMBER
     {325, 11}, // 49: conditional_statement (IF) ->  IF '(' exp_assign_op ')' GOTO BASIC_BLOCK ';' ELSE GOTO BASIC_BLOCK ';'
     {326, 3}, // 50: goto_statement (GOTO) ->  GOTO BASIC_BLOCK ';'
     {327, 1}, // 51: modified_variable ->  variable
     {327, 1}, // 52: modified_variable ->  constant
     {328, 3}, // 53: exp_assign_op (ASSIGN_OP) ->  exp_assign_op ASSIGN_OP exp_eq_ne
     {328, 1}, // 54: exp_assign_op ->  exp_eq_ne
     {329, 3}, // 55: exp_eq_ne (EQUAL) ->  exp_eq_ne EQUAL exp_le_lt_ge_gt
     {329, 3}, // 56: exp_eq_ne (NOT_EQUAL) ->  exp_eq_ne NOT_EQUAL exp_le_lt_ge_gt
     {329, 1}, // 57: exp_eq_ne ->  exp_le_lt_ge_gt
     {330, 3}, // 58: exp_le_lt_ge_gt (GE) ->  exp_le_lt_ge_gt GE exp_add_sub
     {330, 3}, // 59: exp_le_lt_ge_gt (GT) ->  exp_le_lt_ge_gt GT exp_add_sub
     {330, 3}, // 60: exp_le_lt_ge_gt (LE) ->  exp_le_lt_ge_gt LE exp_add_sub
     {330, 3}, // 61: exp_le_lt_ge_gt (LT) ->  exp_le_lt_ge_gt LT exp_add_sub
     {330, 1}, // 62: exp_le_lt_ge_gt ->  exp_add_sub
     {331, 3}, // 63: exp_add_sub ('+') ->  exp_add_sub '+' exp_mul_div
     {331, 3}, // 64: exp_add_sub ('-') ->  exp_add_sub '-' exp_mul_div
     {331, 1}, // 65: exp_add_sub ->  exp_mul_div
     {332, 3}, // 66: exp_mul_div ('*') ->  exp_mul_div '*' singleton
     {332, 3}, // 67: exp_mul_div ('/') ->  exp_mul_div '/' singleton
     {332, 1}, // 68: exp_mul_div ->  singleton
     {333, 1}, // 69: singleton ->  function_call_statement
     {333, 4}, // 70: singleton ('(') ->  '(' type ')' function_call_statement
     {333, 1}, // 71: singleton ->  modified_variable
     {333, 2}, // 72: singleton ('-') ->  '-' modified_variable
     {333, 3}, // 73: singleton ('(') ->  '(' exp_assign_op ')'
     {333, 4}, // 74: singleton ('-') ->  '-' '(' exp_assign_op ')'
     {333, 6}, // 75: singleton ('(') ->  '(' type ')' '(' exp_assign_op ')'
     {334, 1}, // 76: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 11} },                              
    { {       300}, {  1} }, // program                   
    { {       313}, {  2} }, // declaration_statement_list
    { {       301}, {  3} }, // function_declaration_list 
    { {       314}, {  4} }, // declaration_statement     
    { {       304}, {  5} }, // function_declaration      
    { {       307}, {  6} }, // type                      
    { {       265}, {  7} }, // VOID                      
    { {       262}, {  8} }, // INTEGER                   
    { {       263}, {  9} }, // FLOAT                     
    { {       264}, { 10} }, // DOUBLE                    
    { {         0}, {  0} },                              
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, {  9} },                             
    { {       301}, { 11} }, // function_declaration_list
    { {       314}, { 12} }, // declaration_statement    
    { {       304}, {  5} }, // function_declaration     
    { {       307}, {  6} }, // type                     
    { {       265}, {  7} }, // VOID                     
    { {       262}, {  8} }, // INTEGER                  
    { {       263}, {  9} }, // FLOAT                    
    { {       264}, { 10} }, // DOUBLE                   
    { {         0}, {  0} },                             
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, { 10} },                        
    { {       302}, { 13} }, // procedure_list      
    { {       304}, { 14} }, // function_declaration
    { {       308}, { 15} }, // procedure           
    { {       307}, { 16} }, // type                
    { {       265}, {  7} }, // VOID                
    { {       260}, { 17} }, // NAME                
    { {       262}, {  8} }, // INTEGER             
    { {       263}, {  9} }, // FLOAT               
    { {       264}, { 10} }, // DOUBLE              
    { {         0}, {  0} },                        
};

SR__ s_4[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 18} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 19} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_8[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_10[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_11[] =
{
    { { REQ_DEF}, {  8} },                        
    { {     303}, { 20} }, // #0001               
    { {     304}, { 14} }, // function_declaration
    { {     307}, { 16} }, // type                
    { {     265}, {  7} }, // VOID                
    { {     262}, {  8} }, // INTEGER             
    { {     263}, {  9} }, // FLOAT               
    { {     264}, { 10} }, // DOUBLE              
    { {       0}, { -2} },                        
};

SR__ s_12[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_13[] =
{
    { { REQ_DEF}, {  3} },             
    { {     308}, { 21} }, // procedure
    { {     260}, { 17} }, // NAME     
    { {       0}, { -3} },             
};

SR__ s_14[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_16[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 22} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 23} }, // '('
    { {         0}, {  0} },       
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        59}, { 24} }, // ';'
    { {        40}, { 25} }, // '('
    { {         0}, {  0} },       
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 26} }, // '('
    { {         0}, {  0} },       
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  4} },                  
    { {       302}, { 27} }, // procedure_list
    { {       308}, { 15} }, // procedure     
    { {       260}, { 17} }, // NAME          
    { {         0}, {  0} },                  
};

SR__ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 25} }, // '('
    { {         0}, {  0} },       
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  8} },                 
    { {       305}, { 28} }, // argument_list
    { {        41}, { 29} }, // ')'          
    { {       306}, { 30} }, // argument     
    { {       307}, { 31} }, // type         
    { {       262}, {  8} }, // INTEGER      
    { {       263}, {  9} }, // FLOAT        
    { {       264}, { 10} }, // DOUBLE       
    { {         0}, {  0} },                 
};

SR__ s_24[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  8} },                 
    { {       305}, { 32} }, // argument_list
    { {        41}, { 33} }, // ')'          
    { {       306}, { 30} }, // argument     
    { {       307}, { 31} }, // type         
    { {       262}, {  8} }, // INTEGER      
    { {       263}, {  9} }, // FLOAT        
    { {       264}, { 10} }, // DOUBLE       
    { {         0}, {  0} },                 
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, {  8} },                 
    { {       305}, { 34} }, // argument_list
    { {        41}, { 35} }, // ')'          
    { {       306}, { 30} }, // argument     
    { {       307}, { 31} }, // type         
    { {       262}, {  8} }, // INTEGER      
    { {       263}, {  9} }, // FLOAT        
    { {       264}, { 10} }, // DOUBLE       
    { {         0}, {  0} },                 
};

SR__ s_27[] =
{
    { { REQ_DEF}, {  3} },             
    { {     308}, { 21} }, // procedure
    { {     260}, { 17} }, // NAME     
    { {       0}, { -1} },             
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 36} }, // ')'
    { {        44}, { 37} }, // ','
    { {         0}, {  0} },       
};

SR__ s_29[] =
{
    { { DEF_RED}, {   2} },         
    { {     311}, {  38} }, // #0003
    { {       0}, { -21} },         
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 39} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 40} }, // ')'
    { {        44}, { 37} }, // ','
    { {         0}, {  0} },       
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 41} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 42} }, // ')'
    { {        44}, { 37} }, // ','
    { {         0}, {  0} },       
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 43} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_36[] =
{
    { { DEF_RED}, {   2} },         
    { {     310}, {  44} }, // #0002
    { {       0}, { -19} },         
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  6} },            
    { {       306}, { 45} }, // argument
    { {       307}, { 31} }, // type    
    { {       262}, {  8} }, // INTEGER 
    { {       263}, {  9} }, // FLOAT   
    { {       264}, { 10} }, // DOUBLE  
    { {         0}, {  0} },            
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       309}, { 46} }, // procedure_body
    { {       123}, { 47} }, // '{'           
    { {         0}, {  0} },                  
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 48} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_41[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 49} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_43[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       309}, { 50} }, // procedure_body
    { {       123}, { 47} }, // '{'           
    { {         0}, {  0} },                  
};

SR__ s_45[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, { 10} },                              
    { {       313}, { 51} }, // declaration_statement_list
    { {       315}, { 52} }, // basic_block_list          
    { {       314}, {  4} }, // declaration_statement     
    { {       316}, { 53} }, // basic_block               
    { {       307}, { 54} }, // type                      
    { {       258}, { 55} }, // BASIC_BLOCK               
    { {       262}, {  8} }, // INTEGER                   
    { {       263}, {  9} }, // FLOAT                     
    { {       264}, { 10} }, // DOUBLE                    
    { {         0}, {  0} },                              
};

SR__ s_48[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_49[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_50[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_51[] =
{
    { { REQ_DEF}, {   7} },                         
    { {     312}, {  56} }, // #0004                
    { {     314}, {  12} }, // declaration_statement
    { {     307}, {  54} }, // type                 
    { {     262}, {   8} }, // INTEGER              
    { {     263}, {   9} }, // FLOAT                
    { {     264}, {  10} }, // DOUBLE               
    { {       0}, { -23} },                         
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 57} }, // '}'        
    { {       316}, { 58} }, // basic_block
    { {       258}, { 55} }, // BASIC_BLOCK
    { {         0}, {  0} },               
};

SR__ s_53[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 59} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        58}, { 60} }, // ':'
    { {         0}, {  0} },       
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       315}, { 61} }, // basic_block_list
    { {       316}, { 53} }, // basic_block     
    { {       258}, { 55} }, // BASIC_BLOCK     
    { {         0}, {  0} },                    
};

SR__ s_57[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 24} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_60[] =
{
    { { DEF_RED}, {   3} },                             
    { {     317}, {  62} }, // executable_statement_list
    { {     319}, {  63} }, // statement_list           
    { {       0}, { -37} },                             
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 64} }, // '}'        
    { {       316}, { 58} }, // basic_block
    { {       258}, { 55} }, // BASIC_BLOCK
    { {         0}, {  0} },               
};

SR__ s_62[] =
{
    { { REQ_DEF}, {   5} },                         
    { {     325}, {  65} }, // conditional_statement
    { {     326}, {  66} }, // goto_statement       
    { {     266}, {  67} }, // IF                   
    { {     268}, {  68} }, // GOTO                 
    { {       0}, { -30} },                         
};

SR__ s_63[] =
{
    { { REQ_DEF}, {   8} },                           
    { {     318}, {  69} }, // return_statement       
    { {     320}, {  70} }, // assignment_statement   
    { {     321}, {  71} }, // function_call_statement
    { {     261}, {  72} }, // RETURN                 
    { {     323}, {  73} }, // variable               
    { {     260}, {  74} }, // NAME                   
    { {      40}, {  75} }, // '('                    
    { {       0}, { -33} },                           
};

SR__ s_64[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_65[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_66[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 76} }, // '('
    { {         0}, {  0} },       
};

SR__ s_68[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       258}, { 77} }, // BASIC_BLOCK
    { {         0}, {  0} },               
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 78} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 79} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_72[] =
{
    { { REQ_DEF}, {  16} },                           
    { {     328}, {  80} }, // exp_assign_op          
    { {     329}, {  81} }, // exp_eq_ne              
    { {     330}, {  82} }, // exp_le_lt_ge_gt        
    { {     331}, {  83} }, // exp_add_sub            
    { {     332}, {  84} }, // exp_mul_div            
    { {     333}, {  85} }, // singleton              
    { {     321}, {  86} }, // function_call_statement
    { {      40}, {  87} }, // '('                    
    { {     327}, {  88} }, // modified_variable      
    { {      45}, {  89} }, // '-'                    
    { {     260}, {  74} }, // NAME                   
    { {     323}, {  90} }, // variable               
    { {     324}, {  91} }, // constant               
    { {     257}, {  92} }, // INTEGER_NUMBER         
    { {     259}, {  93} }, // FLOATING_POINT_NUMBER  
    { {       0}, { -35} },                           
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       269}, { 94} }, // ASSIGN_OP
    { {         0}, {  0} },             
};

SR__ s_74[] =
{
    { { REQ_DEF}, {   2} },       
    { {      40}, {  95} }, // '('
    { {       0}, { -45} },       
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {  5} },           
    { {       307}, { 96} }, // type   
    { {       262}, {  8} }, // INTEGER
    { {       263}, {  9} }, // FLOAT  
    { {       264}, { 10} }, // DOUBLE 
    { {         0}, {  0} },           
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, { 16} },                           
    { {       328}, { 97} }, // exp_assign_op          
    { {       329}, { 81} }, // exp_eq_ne              
    { {       330}, { 82} }, // exp_le_lt_ge_gt        
    { {       331}, { 83} }, // exp_add_sub            
    { {       332}, { 84} }, // exp_mul_div            
    { {       333}, { 85} }, // singleton              
    { {       321}, { 86} }, // function_call_statement
    { {        40}, { 87} }, // '('                    
    { {       327}, { 88} }, // modified_variable      
    { {        45}, { 89} }, // '-'                    
    { {       260}, { 74} }, // NAME                   
    { {       323}, { 90} }, // variable               
    { {       324}, { 91} }, // constant               
    { {       257}, { 92} }, // INTEGER_NUMBER         
    { {       259}, { 93} }, // FLOATING_POINT_NUMBER  
    { {         0}, {  0} },                           
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 98} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_78[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_80[] =
{
    { { REQ_DEF}, {   2} },             
    { {     269}, {  99} }, // ASSIGN_OP
    { {       0}, { -36} },             
};

SR__ s_81[] =
{
    { { REQ_DEF}, {   3} },             
    { {     271}, { 100} }, // EQUAL    
    { {     270}, { 101} }, // NOT_EQUAL
    { {       0}, { -54} },             
};

SR__ s_82[] =
{
    { { REQ_DEF}, {   5} },      
    { {     275}, { 102} }, // GE
    { {     274}, { 103} }, // GT
    { {     273}, { 104} }, // LE
    { {     272}, { 105} }, // LT
    { {       0}, { -57} },      
};

SR__ s_83[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, { 106} }, // '+'
    { {      45}, { 107} }, // '-'
    { {       0}, { -62} },       
};

SR__ s_84[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, { 108} }, // '*'
    { {      47}, { 109} }, // '/'
    { {       0}, { -65} },       
};

SR__ s_85[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -68} }, 
};

SR__ s_86[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -69} }, 
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, {  20} },                           
    { {       307}, { 110} }, // type                   
    { {       328}, { 111} }, // exp_assign_op          
    { {       262}, {   8} }, // INTEGER                
    { {       263}, {   9} }, // FLOAT                  
    { {       264}, {  10} }, // DOUBLE                 
    { {       329}, {  81} }, // exp_eq_ne              
    { {       330}, {  82} }, // exp_le_lt_ge_gt        
    { {       331}, {  83} }, // exp_add_sub            
    { {       332}, {  84} }, // exp_mul_div            
    { {       333}, {  85} }, // singleton              
    { {       321}, {  86} }, // function_call_statement
    { {        40}, {  87} }, // '('                    
    { {       327}, {  88} }, // modified_variable      
    { {        45}, {  89} }, // '-'                    
    { {       260}, {  74} }, // NAME                   
    { {       323}, {  90} }, // variable               
    { {       324}, {  91} }, // constant               
    { {       257}, {  92} }, // INTEGER_NUMBER         
    { {       259}, {  93} }, // FLOATING_POINT_NUMBER  
    { {         0}, {   0} },                           
};

SR__ s_88[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -71} }, 
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, {   8} },                         
    { {       327}, { 112} }, // modified_variable    
    { {        40}, { 113} }, // '('                  
    { {       323}, {  90} }, // variable             
    { {       324}, {  91} }, // constant             
    { {       260}, { 114} }, // NAME                 
    { {       257}, {  92} }, // INTEGER_NUMBER       
    { {       259}, {  93} }, // FLOATING_POINT_NUMBER
    { {         0}, {   0} },                         
};

SR__ s_90[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_91[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_92[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_93[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_94[] =
{
    { { REQ_TOKEN}, {  16} },                           
    { {       328}, { 115} }, // exp_assign_op          
    { {       329}, {  81} }, // exp_eq_ne              
    { {       330}, {  82} }, // exp_le_lt_ge_gt        
    { {       331}, {  83} }, // exp_add_sub            
    { {       332}, {  84} }, // exp_mul_div            
    { {       333}, {  85} }, // singleton              
    { {       321}, {  86} }, // function_call_statement
    { {        40}, {  87} }, // '('                    
    { {       327}, {  88} }, // modified_variable      
    { {        45}, {  89} }, // '-'                    
    { {       260}, {  74} }, // NAME                   
    { {       323}, {  90} }, // variable               
    { {       324}, {  91} }, // constant               
    { {       257}, {  92} }, // INTEGER_NUMBER         
    { {       259}, {  93} }, // FLOATING_POINT_NUMBER  
    { {         0}, {   0} },                           
};

SR__ s_95[] =
{
    { { REQ_TOKEN}, {  18} },                           
    { {       322}, { 116} }, // exp_assign_op_list     
    { {        41}, { 117} }, // ')'                    
    { {       328}, { 118} }, // exp_assign_op          
    { {       329}, {  81} }, // exp_eq_ne              
    { {       330}, {  82} }, // exp_le_lt_ge_gt        
    { {       331}, {  83} }, // exp_add_sub            
    { {       332}, {  84} }, // exp_mul_div            
    { {       333}, {  85} }, // singleton              
    { {       321}, {  86} }, // function_call_statement
    { {        40}, {  87} }, // '('                    
    { {       327}, {  88} }, // modified_variable      
    { {        45}, {  89} }, // '-'                    
    { {       260}, {  74} }, // NAME                   
    { {       323}, {  90} }, // variable               
    { {       324}, {  91} }, // constant               
    { {       257}, {  92} }, // INTEGER_NUMBER         
    { {       259}, {  93} }, // FLOATING_POINT_NUMBER  
    { {         0}, {   0} },                           
};

SR__ s_96[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 119} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_97[] =
{
    { { REQ_TOKEN}, {   3} },             
    { {        41}, { 120} }, // ')'      
    { {       269}, {  99} }, // ASSIGN_OP
    { {         0}, {   0} },             
};

SR__ s_98[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_99[] =
{
    { { REQ_TOKEN}, {  15} },                           
    { {       329}, { 121} }, // exp_eq_ne              
    { {       330}, {  82} }, // exp_le_lt_ge_gt        
    { {       331}, {  83} }, // exp_add_sub            
    { {       332}, {  84} }, // exp_mul_div            
    { {       333}, {  85} }, // singleton              
    { {       321}, {  86} }, // function_call_statement
    { {        40}, {  87} }, // '('                    
    { {       327}, {  88} }, // modified_variable      
    { {        45}, {  89} }, // '-'                    
    { {       260}, {  74} }, // NAME                   
    { {       323}, {  90} }, // variable               
    { {       324}, {  91} }, // constant               
    { {       257}, {  92} }, // INTEGER_NUMBER         
    { {       259}, {  93} }, // FLOATING_POINT_NUMBER  
    { {         0}, {   0} },                           
};

SR__ s_100[] =
{
    { { REQ_TOKEN}, {  14} },                           
    { {       330}, { 122} }, // exp_le_lt_ge_gt        
    { {       331}, {  83} }, // exp_add_sub            
    { {       332}, {  84} }, // exp_mul_div            
    { {       333}, {  85} }, // singleton              
    { {       321}, {  86} }, // function_call_statement
    { {        40}, {  87} }, // '('                    
    { {       327}, {  88} }, // modified_variable      
    { {        45}, {  89} }, // '-'                    
    { {       260}, {  74} }, // NAME                   
    { {       323}, {  90} }, // variable               
    { {       324}, {  91} }, // constant               
    { {       257}, {  92} }, // INTEGER_NUMBER         
    { {       259}, {  93} }, // FLOATING_POINT_NUMBER  
    { {         0}, {   0} },                           
};

SR__ s_101[] =
{
    { { REQ_TOKEN}, {  14} },                           
    { {       330}, { 123} }, // exp_le_lt_ge_gt        
    { {       331}, {  83} }, // exp_add_sub            
    { {       332}, {  84} }, // exp_mul_div            
    { {       333}, {  85} }, // singleton              
    { {       321}, {  86} }, // function_call_statement
    { {        40}, {  87} }, // '('                    
    { {       327}, {  88} }, // modified_variable      
    { {        45}, {  89} }, // '-'                    
    { {       260}, {  74} }, // NAME                   
    { {       323}, {  90} }, // variable               
    { {       324}, {  91} }, // constant               
    { {       257}, {  92} }, // INTEGER_NUMBER         
    { {       259}, {  93} }, // FLOATING_POINT_NUMBER  
    { {         0}, {   0} },                           
};

SR__ s_102[] =
{
    { { REQ_TOKEN}, {  13} },                           
    { {       331}, { 124} }, // exp_add_sub            
    { {       332}, {  84} }, // exp_mul_div            
    { {       333}, {  85} }, // singleton              
    { {       321}, {  86} }, // function_call_statement
    { {        40}, {  87} }, // '('                    
    { {       327}, {  88} }, // modified_variable      
    { {        45}, {  89} }, // '-'                    
    { {       260}, {  74} }, // NAME                   
    { {       323}, {  90} }, // variable               
    { {       324}, {  91} }, // constant               
    { {       257}, {  92} }, // INTEGER_NUMBER         
    { {       259}, {  93} }, // FLOATING_POINT_NUMBER  
    { {         0}, {   0} },                           
};

SR__ s_103[] =
{
    { { REQ_TOKEN}, {  13} },                           
    { {       331}, { 125} }, // exp_add_sub            
    { {       332}, {  84} }, // exp_mul_div            
    { {       333}, {  85} }, // singleton              
    { {       321}, {  86} }, // function_call_statement
    { {        40}, {  87} }, // '('                    
    { {       327}, {  88} }, // modified_variable      
    { {        45}, {  89} }, // '-'                    
    { {       260}, {  74} }, // NAME                   
    { {       323}, {  90} }, // variable               
    { {       324}, {  91} }, // constant               
    { {       257}, {  92} }, // INTEGER_NUMBER         
    { {       259}, {  93} }, // FLOATING_POINT_NUMBER  
    { {         0}, {   0} },                           
};

SR__ s_104[] =
{
    { { REQ_TOKEN}, {  13} },                           
    { {       331}, { 126} }, // exp_add_sub            
    { {       332}, {  84} }, // exp_mul_div            
    { {       333}, {  85} }, // singleton              
    { {       321}, {  86} }, // function_call_statement
    { {        40}, {  87} }, // '('                    
    { {       327}, {  88} }, // modified_variable      
    { {        45}, {  89} }, // '-'                    
    { {       260}, {  74} }, // NAME                   
    { {       323}, {  90} }, // variable               
    { {       324}, {  91} }, // constant               
    { {       257}, {  92} }, // INTEGER_NUMBER         
    { {       259}, {  93} }, // FLOATING_POINT_NUMBER  
    { {         0}, {   0} },                           
};

SR__ s_105[] =
{
    { { REQ_TOKEN}, {  13} },                           
    { {       331}, { 127} }, // exp_add_sub            
    { {       332}, {  84} }, // exp_mul_div            
    { {       333}, {  85} }, // singleton              
    { {       321}, {  86} }, // function_call_statement
    { {        40}, {  87} }, // '('                    
    { {       327}, {  88} }, // modified_variable      
    { {        45}, {  89} }, // '-'                    
    { {       260}, {  74} }, // NAME                   
    { {       323}, {  90} }, // variable               
    { {       324}, {  91} }, // constant               
    { {       257}, {  92} }, // INTEGER_NUMBER         
    { {       259}, {  93} }, // FLOATING_POINT_NUMBER  
    { {         0}, {   0} },                           
};

SR__ s_106[] =
{
    { { REQ_TOKEN}, {  12} },                           
    { {       332}, { 128} }, // exp_mul_div            
    { {       333}, {  85} }, // singleton              
    { {       321}, {  86} }, // function_call_statement
    { {        40}, {  87} }, // '('                    
    { {       327}, {  88} }, // modified_variable      
    { {        45}, {  89} }, // '-'                    
    { {       260}, {  74} }, // NAME                   
    { {       323}, {  90} }, // variable               
    { {       324}, {  91} }, // constant               
    { {       257}, {  92} }, // INTEGER_NUMBER         
    { {       259}, {  93} }, // FLOATING_POINT_NUMBER  
    { {         0}, {   0} },                           
};

SR__ s_107[] =
{
    { { REQ_TOKEN}, {  12} },                           
    { {       332}, { 129} }, // exp_mul_div            
    { {       333}, {  85} }, // singleton              
    { {       321}, {  86} }, // function_call_statement
    { {        40}, {  87} }, // '('                    
    { {       327}, {  88} }, // modified_variable      
    { {        45}, {  89} }, // '-'                    
    { {       260}, {  74} }, // NAME                   
    { {       323}, {  90} }, // variable               
    { {       324}, {  91} }, // constant               
    { {       257}, {  92} }, // INTEGER_NUMBER         
    { {       259}, {  93} }, // FLOATING_POINT_NUMBER  
    { {         0}, {   0} },                           
};

SR__ s_108[] =
{
    { { REQ_TOKEN}, {  11} },                           
    { {       333}, { 130} }, // singleton              
    { {       321}, {  86} }, // function_call_statement
    { {        40}, {  87} }, // '('                    
    { {       327}, {  88} }, // modified_variable      
    { {        45}, {  89} }, // '-'                    
    { {       260}, {  74} }, // NAME                   
    { {       323}, {  90} }, // variable               
    { {       324}, {  91} }, // constant               
    { {       257}, {  92} }, // INTEGER_NUMBER         
    { {       259}, {  93} }, // FLOATING_POINT_NUMBER  
    { {         0}, {   0} },                           
};

SR__ s_109[] =
{
    { { REQ_TOKEN}, {  11} },                           
    { {       333}, { 131} }, // singleton              
    { {       321}, {  86} }, // function_call_statement
    { {        40}, {  87} }, // '('                    
    { {       327}, {  88} }, // modified_variable      
    { {        45}, {  89} }, // '-'                    
    { {       260}, {  74} }, // NAME                   
    { {       323}, {  90} }, // variable               
    { {       324}, {  91} }, // constant               
    { {       257}, {  92} }, // INTEGER_NUMBER         
    { {       259}, {  93} }, // FLOATING_POINT_NUMBER  
    { {         0}, {   0} },                           
};

SR__ s_110[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 132} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_111[] =
{
    { { REQ_TOKEN}, {   3} },             
    { {        41}, { 133} }, // ')'      
    { {       269}, {  99} }, // ASSIGN_OP
    { {         0}, {   0} },             
};

SR__ s_112[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -72} }, 
};

SR__ s_113[] =
{
    { { REQ_TOKEN}, {  20} },                           
    { {       328}, { 134} }, // exp_assign_op          
    { {       307}, {  96} }, // type                   
    { {       329}, {  81} }, // exp_eq_ne              
    { {       262}, {   8} }, // INTEGER                
    { {       263}, {   9} }, // FLOAT                  
    { {       264}, {  10} }, // DOUBLE                 
    { {       330}, {  82} }, // exp_le_lt_ge_gt        
    { {       331}, {  83} }, // exp_add_sub            
    { {       332}, {  84} }, // exp_mul_div            
    { {       333}, {  85} }, // singleton              
    { {       321}, {  86} }, // function_call_statement
    { {        40}, {  87} }, // '('                    
    { {       327}, {  88} }, // modified_variable      
    { {        45}, {  89} }, // '-'                    
    { {       260}, {  74} }, // NAME                   
    { {       323}, {  90} }, // variable               
    { {       324}, {  91} }, // constant               
    { {       257}, {  92} }, // INTEGER_NUMBER         
    { {       259}, {  93} }, // FLOATING_POINT_NUMBER  
    { {         0}, {   0} },                           
};

SR__ s_114[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_115[] =
{
    { { REQ_TOKEN}, {   3} },             
    { {        59}, { 135} }, // ';'      
    { {       269}, {  99} }, // ASSIGN_OP
    { {         0}, {   0} },             
};

SR__ s_116[] =
{
    { { REQ_TOKEN}, {   3} },       
    { {        41}, { 136} }, // ')'
    { {        44}, { 137} }, // ','
    { {         0}, {   0} },       
};

SR__ s_117[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_118[] =
{
    { { REQ_DEF}, {   2} },             
    { {     269}, {  99} }, // ASSIGN_OP
    { {       0}, { -44} },             
};

SR__ s_119[] =
{
    { { REQ_TOKEN}, {   2} },        
    { {       260}, { 138} }, // NAME
    { {         0}, {   0} },        
};

SR__ s_120[] =
{
    { { REQ_TOKEN}, {   2} },        
    { {       268}, { 139} }, // GOTO
    { {         0}, {   0} },        
};

SR__ s_121[] =
{
    { { REQ_DEF}, {   3} },             
    { {     271}, { 100} }, // EQUAL    
    { {     270}, { 101} }, // NOT_EQUAL
    { {       0}, { -53} },             
};

SR__ s_122[] =
{
    { { REQ_DEF}, {   5} },      
    { {     275}, { 102} }, // GE
    { {     274}, { 103} }, // GT
    { {     273}, { 104} }, // LE
    { {     272}, { 105} }, // LT
    { {       0}, { -55} },      
};

SR__ s_123[] =
{
    { { REQ_DEF}, {   5} },      
    { {     275}, { 102} }, // GE
    { {     274}, { 103} }, // GT
    { {     273}, { 104} }, // LE
    { {     272}, { 105} }, // LT
    { {       0}, { -56} },      
};

SR__ s_124[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, { 106} }, // '+'
    { {      45}, { 107} }, // '-'
    { {       0}, { -58} },       
};

SR__ s_125[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, { 106} }, // '+'
    { {      45}, { 107} }, // '-'
    { {       0}, { -59} },       
};

SR__ s_126[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, { 106} }, // '+'
    { {      45}, { 107} }, // '-'
    { {       0}, { -60} },       
};

SR__ s_127[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, { 106} }, // '+'
    { {      45}, { 107} }, // '-'
    { {       0}, { -61} },       
};

SR__ s_128[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, { 108} }, // '*'
    { {      47}, { 109} }, // '/'
    { {       0}, { -63} },       
};

SR__ s_129[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, { 108} }, // '*'
    { {      47}, { 109} }, // '/'
    { {       0}, { -64} },       
};

SR__ s_130[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -66} }, 
};

SR__ s_131[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -67} }, 
};

SR__ s_132[] =
{
    { { REQ_TOKEN}, {   4} },                           
    { {       321}, { 140} }, // function_call_statement
    { {        40}, { 141} }, // '('                    
    { {       260}, { 142} }, // NAME                   
    { {         0}, {   0} },                           
};

SR__ s_133[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -73} }, 
};

SR__ s_134[] =
{
    { { REQ_TOKEN}, {   3} },             
    { {        41}, { 143} }, // ')'      
    { {       269}, {  99} }, // ASSIGN_OP
    { {         0}, {   0} },             
};

SR__ s_135[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_136[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_137[] =
{
    { { REQ_TOKEN}, {  16} },                           
    { {       328}, { 144} }, // exp_assign_op          
    { {       329}, {  81} }, // exp_eq_ne              
    { {       330}, {  82} }, // exp_le_lt_ge_gt        
    { {       331}, {  83} }, // exp_add_sub            
    { {       332}, {  84} }, // exp_mul_div            
    { {       333}, {  85} }, // singleton              
    { {       321}, {  86} }, // function_call_statement
    { {        40}, {  87} }, // '('                    
    { {       327}, {  88} }, // modified_variable      
    { {        45}, {  89} }, // '-'                    
    { {       260}, {  74} }, // NAME                   
    { {       323}, {  90} }, // variable               
    { {       324}, {  91} }, // constant               
    { {       257}, {  92} }, // INTEGER_NUMBER         
    { {       259}, {  93} }, // FLOATING_POINT_NUMBER  
    { {         0}, {   0} },                           
};

SR__ s_138[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_139[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       258}, { 145} }, // BASIC_BLOCK
    { {         0}, {   0} },               
};

SR__ s_140[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -70} }, 
};

SR__ s_141[] =
{
    { { REQ_TOKEN}, {  16} },                           
    { {       328}, { 146} }, // exp_assign_op          
    { {       329}, {  81} }, // exp_eq_ne              
    { {       330}, {  82} }, // exp_le_lt_ge_gt        
    { {       331}, {  83} }, // exp_add_sub            
    { {       332}, {  84} }, // exp_mul_div            
    { {       333}, {  85} }, // singleton              
    { {       321}, {  86} }, // function_call_statement
    { {        40}, {  87} }, // '('                    
    { {       327}, {  88} }, // modified_variable      
    { {        45}, {  89} }, // '-'                    
    { {       260}, {  74} }, // NAME                   
    { {       323}, {  90} }, // variable               
    { {       324}, {  91} }, // constant               
    { {       257}, {  92} }, // INTEGER_NUMBER         
    { {       259}, {  93} }, // FLOATING_POINT_NUMBER  
    { {         0}, {   0} },                           
};

SR__ s_142[] =
{
    { { REQ_DEF}, {   2} },       
    { {      40}, {  95} }, // '('
    { {       0}, { -46} },       
};

SR__ s_143[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -74} }, 
};

SR__ s_144[] =
{
    { { REQ_DEF}, {   2} },             
    { {     269}, {  99} }, // ASSIGN_OP
    { {       0}, { -43} },             
};

SR__ s_145[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 147} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_146[] =
{
    { { REQ_TOKEN}, {   3} },             
    { {        41}, { 148} }, // ')'      
    { {       269}, {  99} }, // ASSIGN_OP
    { {         0}, {   0} },             
};

SR__ s_147[] =
{
    { { REQ_TOKEN}, {   2} },        
    { {       267}, { 149} }, // ELSE
    { {         0}, {   0} },        
};

SR__ s_148[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -75} }, 
};

SR__ s_149[] =
{
    { { REQ_TOKEN}, {   2} },        
    { {       268}, { 150} }, // GOTO
    { {         0}, {   0} },        
};

SR__ s_150[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       258}, { 151} }, // BASIC_BLOCK
    { {         0}, {   0} },               
};

SR__ s_151[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 152} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_152[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,  s_139,
  s_140,  s_141,  s_142,  s_143,  s_144,  s_145,  s_146,  s_147,  s_148,  s_149,
  s_150,  s_151,  s_152,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
        {
         Procedure * main_procedure = program_object.get_main_procedure(cout);
         if (main_procedure == NULL) 
         {
         int line = get_line_number();
         report_error("No main procedure defined",line);
         }
         bool ret = program_object.check_all_functions_defined();
         
         if (!ret) {
         int line = get_line_number();
         report_error("Function declared but not defined",line);
         }
         program_object.check_all_functions_returned();
         if (d_vsp__[-3].symbol_table)
         d_vsp__[-3].symbol_table->global_list_in_proc_map_check(get_line_number());
         delete d_vsp__[-3].symbol_table;
         }
        break;

        case 2:
        d_val__ = d_vsp__[-1];
        {
         program_object.set_global_table(*d_vsp__[-1].symbol_table);
         return_statement_used_flag = false; 
         }
        break;

        case 3:
        {
         Procedure * main_procedure = program_object.get_main_procedure(cout);
         if (main_procedure == NULL) 
         {
         int line = get_line_number();
         report_error("No main procedure defined",line);
         }
         bool ret = program_object.check_all_functions_defined();
         
         if (!ret) {
         int line = get_line_number();
         report_error("Function declared but not defined",line);
         }
         program_object.check_all_functions_returned();
         }
        break;

        case 4:
        {
         }
        break;

        case 5:
        {
         }
        break;

        case 6:
        {
         Procedure * current_procedure = new Procedure (d_vsp__[-5].D, *(d_vsp__[-4].string_value), *(d_vsp__[-2].list_of_argument));
         
         bool ret = program_object.set_procedure_map(*current_procedure);
         if (program_object.variable_in_symbol_list_check(*(d_vsp__[-4].string_value))) {
         int line = get_line_number();
         report_error("Function name the same as that of a global",line);
         }
         if (!ret) { 
         int line = get_line_number();
         report_error("Function already defined, overloading not allowed",line);
         }
         }
        break;

        case 7:
        {
         Procedure * current_procedure = new Procedure (void_data_type, *(d_vsp__[-4].string_value), *(d_vsp__[-2].list_of_argument));
         
         bool ret = program_object.set_procedure_map(*current_procedure);
         if (program_object.variable_in_symbol_list_check(*(d_vsp__[-4].string_value))) {
         int line = get_line_number();
         report_error("Function name the same as that of a global",line);
         }
         if (!ret) { 
         int line = get_line_number();
         report_error("Function already defined, overloading not allowed",line);
         }
         }
        break;

        case 8:
        {
         Procedure * current_procedure = new Procedure (d_vsp__[-4].D, *(d_vsp__[-3].string_value), *(new (list <argument*>)));
         
         bool ret = program_object.set_procedure_map(*current_procedure);
         if (program_object.variable_in_symbol_list_check(*(d_vsp__[-3].string_value))) {
         int line = get_line_number();
         report_error("Function name the same as that of a global",line);
         }
         if (!ret) { 
         int line = get_line_number();
         report_error("Function already defined, overloading not allowed",line);
         }
         }
        break;

        case 9:
        {
         Procedure * current_procedure = new Procedure (void_data_type, *(d_vsp__[-3].string_value), *(new (list<argument*>)));
         
         bool ret = program_object.set_procedure_map(*current_procedure);
         if (program_object.variable_in_symbol_list_check(*(d_vsp__[-3].string_value))) {
         int line = get_line_number();
         report_error("Function name the same as that of a global",line);
         }
         if (!ret) { 
         int line = get_line_number();
         report_error("Function already defined, overloading not allowed",line);
         }
         }
        break;

        case 10:
        {
         d_val__.list_of_argument= d_vsp__[-2].list_of_argument;
         d_val__.list_of_argument->push_back (d_vsp__[0].argument_obj);
         }
        break;

        case 11:
        {
         d_val__.list_of_argument= new (list <argument*>);
         d_val__.list_of_argument->push_back(d_vsp__[0].argument_obj);
         }
        break;

        case 12:
        {
         d_val__.argument_obj= new argument (d_vsp__[-1].D, *(d_vsp__[0].string_value));
         }
        break;

        case 13:
        {
         d_val__.D= int_data_type;
         }
        break;

        case 14:
        {
         d_val__.D= float_data_type;
         }
        break;

        case 15:
        {
         d_val__.D= double_data_type;
         }
        break;

        case 16:
        {
         }
        break;

        case 17:
        {
         }
        break;

        case 18:
        {
         
         
         
         }
        break;

        case 19:
        d_val__ = d_vsp__[-3];
        {
         current_procedure = program_object.get_procedure(*d_vsp__[-3].string_value);
         if (current_procedure == NULL) {
         int line = get_line_number();
         report_error("Function declaration not present",line);
         }
         
         if (!current_procedure->match_argument_list(d_vsp__[-1].list_of_argument))
         {
         int line = get_line_number();
         report_error("Failed to match argument list", line);
         }
         current_procedure->push_arguments_into_symbol_table();
         program_object.push_to_list(*d_vsp__[-3].string_value);
         }
        break;

        case 20:
        {
         
         
         
         
         
         
         }
        break;

        case 21:
        d_val__ = d_vsp__[-2];
        {
         current_procedure = program_object.get_procedure(*d_vsp__[-2].string_value);
         if (current_procedure == NULL) {
         int line = get_line_number();
         report_error("Function declaration not present",line);
         }
         
         if (!current_procedure->match_argument_list(NULL)) {
         int line = get_line_number();
         report_error("Failed to match argument list", line);
         }
         program_object.push_to_list(*d_vsp__[-2].string_value);
         }
        break;

        case 22:
        {
         
         
          
          
          
          
          
         
         
         if (max_bb_num < max_goto_bb_num)
         {
         int line = get_line_number();
         report_error("Basic block does not exist", line);
         }
         
         current_procedure->set_basic_block_list(*(d_vsp__[-1].basic_block_list));
         delete d_vsp__[-1].basic_block_list;
         }
        break;

        case 23:
        d_val__ = d_vsp__[-1];
        {
         current_procedure->set_local_list(*d_vsp__[0].symbol_table);
         current_procedure->push_arguments_into_symbol_table();
         delete d_vsp__[0].symbol_table;
         }
        break;

        case 24:
        {
         
          
          
          
          
          
         
         if (max_bb_num < max_goto_bb_num)
         {
         int line = get_line_number();
         report_error("Basic block does not exist", line);
         }
         
         current_procedure->set_basic_block_list(*(d_vsp__[-1].basic_block_list));
         delete d_vsp__[-1].basic_block_list;
         }
        break;

        case 25:
        {
         
         int line = get_line_number();
         program_object.variable_in_proc_map_check(d_vsp__[0].symbol_entry->get_variable_name(), line);
         string var_name = d_vsp__[0].symbol_entry->get_variable_name();
         if (program_object.get_procedure(var_name) != NULL)
         {
         int line = get_line_number();
         report_error("Variable name cannot be same as procedure name", line);
         }
         d_val__.symbol_table = new Symbol_Table();
         d_val__.symbol_table->push_symbol(d_vsp__[0].symbol_entry);
         }
        break;

        case 26:
        {
         
         
         
         
         int line = get_line_number();
         program_object.variable_in_proc_map_check(d_vsp__[0].symbol_entry->get_variable_name(), line);
         string var_name = d_vsp__[0].symbol_entry->get_variable_name();
         if (program_object.get_procedure(var_name) != NULL)
         {
         int line = get_line_number();
         report_error("Variable name cannot be same as procedure name", line);
         }
         if (d_vsp__[-1].symbol_table != NULL)
         {
         if(d_vsp__[-1].symbol_table->variable_in_symbol_list_check(var_name))
         {
         int line = get_line_number();
         report_error("Variable is declared twice", line);
         }
         d_val__.symbol_table = d_vsp__[-1].symbol_table;
         }
         else
         d_val__.symbol_table = new Symbol_Table();
         d_val__.symbol_table->push_symbol(d_vsp__[0].symbol_entry);
         }
        break;

        case 27:
        {
         d_val__.symbol_entry = new Symbol_Table_Entry(*(d_vsp__[-1].string_value), d_vsp__[-2].D);
         delete d_vsp__[-1].string_value;
         }
        break;

        case 28:
        {
         
         if (!d_vsp__[0].basic_block)
         {
         int line = get_line_number();
         report_error("Basic block doesn't exist", line);
         }
         bb_strictly_increasing_order_check(current_procedure->get_and_increment_basic_block_number(), d_vsp__[0].basic_block->get_bb_number());
         d_val__.basic_block_list = d_vsp__[-1].basic_block_list;
         d_val__.basic_block_list->push_back(d_vsp__[0].basic_block);
         max_bb_num = max (d_vsp__[0].basic_block->get_bb_number(), max_bb_num);
         }
        break;

        case 29:
        {
         
         if (!d_vsp__[0].basic_block)
         {
         int line = get_line_number();
         report_error("Basic block doesn't exist", line);
         }
         bb_strictly_increasing_order_check(current_procedure->get_and_increment_basic_block_number(), d_vsp__[0].basic_block->get_bb_number());
         max_bb_num = max (d_vsp__[0].basic_block->get_bb_number(), max_bb_num);
         d_val__.basic_block_list = new list<Basic_Block *>;
         d_val__.basic_block_list->push_back(d_vsp__[0].basic_block);
         }
        break;

        case 30:
        {
         
         int i = 0;
         for (; (*d_vsp__[-2].string_value)[i] != ' '; ++i) {
         
         }
         ++i;
         int id = 0;
         for (; (*d_vsp__[-2].string_value)[i] != '>'; ++i) {
         id = id *10 + ((*d_vsp__[-2].string_value)[i]-'0');
         }
         if (d_vsp__[0].ast_list!= NULL)
         d_val__.basic_block= new Basic_Block (id, *d_vsp__[0].ast_list);
         else {
         list<Ast *> * ast_list = new list<Ast *>;
         d_val__.basic_block= new Basic_Block (id, *ast_list);
         }
         delete d_vsp__[0].ast_list;
         }
        break;

        case 31:
        {
         
         int i = 0;
         for (; (*d_vsp__[-3].string_value)[i] != ' '; ++i) {
         
         }
         ++i;
         int id = 0;
         for (; (*d_vsp__[-3].string_value)[i] != '>'; ++i) {
         id = id *10 + ((*d_vsp__[-3].string_value)[i]-'0');
         }
         
         if (d_vsp__[-1].ast_list != NULL)
         {
         d_vsp__[-1].ast_list->push_back (d_vsp__[0].ast);
         d_val__.basic_block = new Basic_Block(id, *d_vsp__[-1].ast_list);
         }
         else
         {
         list<Ast *> * ast_list = new list<Ast *>;
         ast_list->push_back (d_vsp__[0].ast);
         d_val__.basic_block = new Basic_Block(id, *ast_list);
         }
         delete d_vsp__[-1].ast_list;
         }
        break;

        case 32:
        {
         
         int i = 0;
         for (; (*(d_vsp__[-3].string_value))[i] != ' '; ++i) {
         
         }
         ++i;
         int id = 0;
         for (; (*(d_vsp__[-3].string_value))[i] != '>'; ++i) {
         id = id *10 + ((*(d_vsp__[-3].string_value))[i]-'0');
         }
         
         if (d_vsp__[-1].ast_list != NULL)
         {
         d_vsp__[-1].ast_list->push_back (d_vsp__[0].ast);
         d_val__.basic_block = new Basic_Block(id, *d_vsp__[-1].ast_list);
         }
         else
         {
         list<Ast *> * ast_list = new list<Ast *>;
         ast_list->push_back (d_vsp__[0].ast);
         d_val__.basic_block = new Basic_Block(id, *ast_list);
         }
         delete d_vsp__[-1].ast_list;
         }
        break;

        case 33:
        {
         
         d_val__.ast_list = d_vsp__[0].ast_list;
         }
        break;

        case 34:
        {
         return_statement_used_flag = true; 
         if (d_vsp__[-2].ast_list != NULL)
         d_val__.ast_list = d_vsp__[-2].ast_list;
         else
         d_val__.ast_list = new list<Ast *>;
         d_val__.ast_list->push_back(d_vsp__[-1].ast);
         }
        break;

        case 35:
        {
         d_val__.ast = new Return_Ast(NULL);
         }
        break;

        case 36:
        {
         int line = get_line_number();
         bool ret = current_procedure->check_return_type (d_vsp__[0].ast->get_data_type());
         if (!ret) {
         report_error("Return type mismatch error",line);
         }
         d_val__.ast = new Return_Ast(d_vsp__[0].ast);
         }
        break;

        case 37:
        {
         d_val__.ast_list = NULL;
         }
        break;

        case 38:
        {
         if (d_vsp__[-1].ast_list == NULL)
         d_val__.ast_list = new list<Ast *>;
         else
         d_val__.ast_list = d_vsp__[-1].ast_list;
         d_val__.ast_list->push_back(d_vsp__[0].ast);
         }
        break;

        case 39:
        {
         if (d_vsp__[-2].ast_list == NULL)
         d_val__.ast_list = new list<Ast *>;
         else
         d_val__.ast_list = d_vsp__[-2].ast_list;
         d_val__.ast_list->push_back(d_vsp__[-1].ast);
         }
        break;

        case 40:
        {
         d_val__.ast = new Assignment_Ast(d_vsp__[-3].ast, d_vsp__[-1].ast);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 41:
        {
         d_val__.ast = new Functional_Call_Ast(*d_vsp__[-3].string_value, *d_vsp__[-1].ast_list);
         Procedure * called_procedure = program_object.get_procedure(*d_vsp__[-3].string_value);
         if (called_procedure == NULL) {
         int line = get_line_number();
         report_error("Function does not exist", line);
         }
         
         if (!called_procedure->match_function_call(d_vsp__[-1].ast_list)) {
         int line = get_line_number();
         report_error("Function call does not match its signature",line);
         }
         d_val__.ast->set_data_type(called_procedure->get_return_type());
         }
        break;

        case 42:
        {
         d_val__.ast = new Functional_Call_Ast(*d_vsp__[-2].string_value, *(new list<Ast*>()));
         Procedure * called_procedure = program_object.get_procedure(*d_vsp__[-2].string_value);
         if (called_procedure == NULL) {
         int line = get_line_number();
         report_error("Function does not exist", line);
         }
         
         if (!called_procedure->match_function_call(NULL)) {
         int line = get_line_number();
         report_error("Function call does not match its signature",line);
         }
         d_val__.ast->set_data_type(called_procedure->get_return_type());
         }
        break;

        case 43:
        {
         d_val__.ast_list = d_vsp__[-2].ast_list;
         d_val__.ast_list->push_back(d_vsp__[0].ast);
         }
        break;

        case 44:
        {
         d_val__.ast_list = new (list<Ast*>);
         d_val__.ast_list->push_back(d_vsp__[0].ast);
         }
        break;

        case 45:
        {
         Symbol_Table_Entry var_table_entry;
         if (current_procedure->variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = current_procedure->get_symbol_table_entry(*d_vsp__[0].string_value);
         else if (program_object.variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = program_object.get_symbol_table_entry(*d_vsp__[0].string_value);
         else
         {
         int line = get_line_number();
         report_error("Variable has not been declared", line);
         }
         d_val__.ast = new Name_Ast(*d_vsp__[0].string_value, var_table_entry);
         delete d_vsp__[0].string_value;
         }
        break;

        case 46:
        {
         Symbol_Table_Entry var_table_entry;
         if (current_procedure->variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = current_procedure->get_symbol_table_entry(*d_vsp__[0].string_value);
         else if (program_object.variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = program_object.get_symbol_table_entry(*d_vsp__[0].string_value);
         else
         {
         int line = get_line_number();
         report_error("Variable has not been declared", line);
         }
         Name_Ast * toCast = new Name_Ast(*d_vsp__[0].string_value, var_table_entry);
         d_val__.ast = new Cast_Name_Ast(toCast, d_vsp__[-2].D);
         delete d_vsp__[0].string_value;
         }
        break;

        case 47:
        {
         d_val__.ast = new Number_Ast<int>(d_vsp__[0].integer_value, int_data_type);
         }
        break;

        case 48:
        {
         d_val__.ast = new Number_Ast<float>(d_vsp__[0].float_value, float_data_type);
         }
        break;

        case 49:
        {
         int i = 0;
         for (; (*(d_vsp__[-5].string_value))[i] != ' '; ++i) {
         
         }
         ++i;
         int id1 = 0;
         for (; (*(d_vsp__[-5].string_value))[i] != '>'; ++i) {
         id1 = id1 *10 + ((*(d_vsp__[-5].string_value))[i]-'0');
         }
         i = 0;
         for (; (*(d_vsp__[-1].string_value))[i] != ' '; ++i) {
         
         }
         ++i;
         int id2 = 0;
         for (; (*(d_vsp__[-1].string_value))[i] != '>'; ++i) {
         id2 = id2 *10 + ((*(d_vsp__[-1].string_value))[i]-'0');
         }
         d_val__.ast = new Conditional_Ast (d_vsp__[-8].ast, id1, id2);
         }
        break;

        case 50:
        {
         int i = 0;
         for (; (*(d_vsp__[-1].string_value))[i] != ' '; ++i) {
         
         }
         ++i;
         int id = 0;
         for (; (*(d_vsp__[-1].string_value))[i] != '>'; ++i) {
         id = id *10 + ((*(d_vsp__[-1].string_value))[i]-'0');
         }
         max_goto_bb_num = max (max_goto_bb_num, id);
         d_val__.ast = new Goto_Ast (id);
         }
        break;

        case 51:
        {
         d_val__.ast = d_vsp__[0].ast;
         }
        break;

        case 52:
        {
         d_val__.ast = d_vsp__[0].ast;
         }
        break;

        case 53:
        {
         
         d_val__.ast = new Expr_Ast (d_vsp__[-2].ast, 1, d_vsp__[0].ast);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 54:
        {
         
         d_val__.ast = d_vsp__[0].ast;
         }
        break;

        case 55:
        {
         
         d_val__.ast = new Expr_Ast (d_vsp__[-2].ast, 7, d_vsp__[0].ast);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 56:
        {
         
         d_val__.ast = new Expr_Ast (d_vsp__[-2].ast, 6, d_vsp__[0].ast);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 57:
        {
         d_val__.ast = d_vsp__[0].ast;
         }
        break;

        case 58:
        {
         d_val__.ast = new Expr_Ast (d_vsp__[-2].ast, 3, d_vsp__[0].ast);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 59:
        {
         d_val__.ast = new Expr_Ast (d_vsp__[-2].ast, 5, d_vsp__[0].ast);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 60:
        {
         d_val__.ast = new Expr_Ast (d_vsp__[-2].ast, 2, d_vsp__[0].ast);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 61:
        {
         d_val__.ast = new Expr_Ast (d_vsp__[-2].ast, 4, d_vsp__[0].ast);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 62:
        {
         d_val__.ast = d_vsp__[0].ast;
         }
        break;

        case 63:
        {
         d_val__.ast = new Expr_Ast (d_vsp__[-2].ast, 8, d_vsp__[0].ast);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 64:
        {
         d_val__.ast = new Expr_Ast (d_vsp__[-2].ast, 9, d_vsp__[0].ast);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 65:
        {
         d_val__.ast = d_vsp__[0].ast;
         }
        break;

        case 66:
        {
         d_val__.ast = new Expr_Ast (d_vsp__[-2].ast, 10, d_vsp__[0].ast);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 67:
        {
         d_val__.ast = new Expr_Ast (d_vsp__[-2].ast, 11, d_vsp__[0].ast);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 68:
        {
         d_val__.ast = d_vsp__[0].ast;
         }
        break;

        case 69:
        {
         d_val__.ast = d_vsp__[0].ast;
         }
        break;

        case 70:
        {
         d_val__.ast = new Cast_Expr_Ast (d_vsp__[0].ast, d_vsp__[-2].D);
         }
        break;

        case 71:
        {
         d_val__.ast = d_vsp__[0].ast;
         }
        break;

        case 72:
        {
         d_val__.ast = new Expr_Ast (d_vsp__[0].ast, 12, NULL);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 73:
        {
         d_val__.ast = d_vsp__[-1].ast;
         }
        break;

        case 74:
        {
         d_val__.ast = new Expr_Ast (d_vsp__[-1].ast, 12, NULL);
         int line = get_line_number();
         d_val__.ast->check_ast(line);
         }
        break;

        case 75:
        {
         
         d_val__.ast = new Cast_Expr_Ast (d_vsp__[-1].ast, d_vsp__[-4].D);
         }
        break;

    }
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}

